modLoader="javafml"
loaderVersion="[4,)"
license="MIT"

[[mods]]
modId="ftbqlang"
version="${mod_version}"
displayName="Quest Language Selection"
authors="AblazeAQZL"
description='''Quest Language Selection'''

[[mixins]]
config="ftbqlang.mixins.json"

[[dependencies.ftbqlang]]
modId="neoforge"
type="required"
versionRange="[21.1.213,)"
ordering="NONE"
side="BOTH"

[[dependencies.ftbqlang]]
modId="minecraft"
type="required"
versionRange="[1.21.1,1.21.2)"
ordering="NONE"
side="BOTH"

[[dependencies.ftbqlang]]
modId="ftbquests"
type="required"
versionRange="[2101.1.27,2102)"
ordering="AFTER"
side="BOTH"

[[dependencies.ftbqlang]]
modId="ftblibrary"
type="required"
versionRange="[2101.1.31,2102)"
ordering="AFTER"
side="BOTH"

[[dependencies.ftbqlang]]
modId="ftbteams"
type="required"
versionRange="[2101.1.9,2102)"
ordering="AFTER"
side="BOTH"

[[dependencies.ftbqlang]]
modId="architectury"
type="required"
versionRange="[13.0.8,14)"
ordering="AFTER"
side="BOTH"
